### ISSUE TITLE
Automate the process of updating the list of entity schemas

### ISSUE THREAD

**Issue by labra** [weso/wikishape#10]
At this moment the list of entity schemas is hard-coded in the code. 

It is taken from the file [`src/resources/schemaEntities.js`](https://github.com/weso/wikishape/blob/master/src/resources/schemaEntities.js) which assigns the list of entities represented in Json to a variable.

It would be better to dynamically obtain that list or to get it from a database but we want to keep wikishape as a client only code. 

In order to generate the list of entities, we created a simple Scala program in repository [wdEntities](https://github.com/weso/wdEntities). Once that program is run, it stores the list of entities in a JSON file whose contents are added to the schemaEntities file.

This process is completely error-prone and manual. Replace this process by a more elegant solution.

**Comment by ulitol97** [comment]
Solved in #44, full story in https://github.com/weso/rdfshape-api/pull/300.
