### ISSUE TITLE
Support to extract a schema from an entity from Wikibase instances

### ISSUE THREAD

**Issue by labra** [weso/wikishape#16]
The option to extract a schema from data works only for Wikidata. When trying with a wikibase instance it complains with this error:

```
http://cursoslabra.wiki.opencura.com/entity/Q1 doesn't match regular expression: http://www.wikidata.org/entity/(.*)
```

So it seems that the extraction of the Q1 from the URI is hardcoded to wikidata. Check how to generalize it.

**Comment by ulitol97** [comment]
Issue solved by implementing support for custom Wikibase instances. See #12 for additional details.

Check this example too, https://wikishape.weso.es/link/16475127673, where a schema is extracted from https://cursoslabra.wiki.opencura.com/wiki/Item:Q2.
