### ISSUE TITLE
Get information about an entity schema from a wikibase instance

### ISSUE THREAD

**Issue by labra** [weso/wikishape#26]
At this moment, when you try the option to get information about an entity schema in wikishape, it auto-completes from wikidata ignoring the settings about other wikibases. It should follow the settings in "Change target wikibase"

**Comment by dlindem** [comment]
I confirm that extract scheme from entities only works with Wikidata, despite changing target wikibase. Would be awesome if you could fix this.

**Comment by ulitol97** [comment]
Unfortunately, MediaWiki's API does not provided a way to fetch schemas from a Wikibase instance thus preventing us from auto-completing schemas as you write them down. This issue has been discussed in #10 and ideas are welcome.

Apart from this, full custom wikibase support has been implemented (full explanation in #12), so @dlindem you may want to give it a shot now (and thanks for the kind words 🥳). A problem like yours was just described and solved in #16.

**Comment by dlindem** [comment]
Wow! Yes, awesome, it works for a custom Wikibase. Muchas gracias.
