### ISSUE TITLE
Can't access "validate" functionalities

### ISSUE THREAD

**Issue by ulitol97** [weso/wikishape#9]
This issue is a parallel issue to https://github.com/weso/rdfshape-client/issues/20.

WikiShape is having the same issues as RDFShape when accessing certain pages. All the issues I found are listed below:

- http://156.35.95.117:8080/wikidataValidate
- http://156.35.95.117:8080/wikidataValidateSPARQL

The response is a blank page and an error similar to the one in RDFShape.

**Comment by labra** [comment]
I think they are solved once we updated the Yashe version.
